# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 793)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.tabWidget.setObjectName("tabWidget")
        self.mainframe = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mainframe.setFont(font)
        self.mainframe.setAutoFillBackground(False)
        self.mainframe.setObjectName("mainframe")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mainframe)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalWidget_2 = QtWidgets.QWidget(self.mainframe)
        self.horizontalWidget_2.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalWidget_2)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(90)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_4.addWidget(self.horizontalWidget_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start = QtWidgets.QPushButton(self.mainframe)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.save = QtWidgets.QPushButton(self.mainframe)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.save.setFont(font)
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)
        self.exit = QtWidgets.QPushButton(self.mainframe)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")
        self.horizontalLayout.addWidget(self.exit)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_4.setStretch(0, 10)
        self.verticalLayout_4.setStretch(1, 1)
        self.tabWidget.addTab(self.mainframe, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.verticalGroupBox.setFont(font)
        self.verticalGroupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.verticalGroupBox.setFlat(False)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.appearTime = QtWidgets.QSpinBox(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.appearTime.setFont(font)
        self.appearTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.appearTime.setMinimum(100)
        self.appearTime.setMaximum(10000)
        self.appearTime.setSingleStep(100)
        self.appearTime.setProperty("value", 400)
        self.appearTime.setObjectName("appearTime")
        self.horizontalLayout_5.addWidget(self.appearTime)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.eraseTime = QtWidgets.QSpinBox(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.eraseTime.setFont(font)
        self.eraseTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.eraseTime.setMinimum(100)
        self.eraseTime.setMaximum(10000)
        self.eraseTime.setSingleStep(100)
        self.eraseTime.setProperty("value", 200)
        self.eraseTime.setObjectName("eraseTime")
        self.horizontalLayout_6.addWidget(self.eraseTime)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3.addWidget(self.verticalGroupBox)
        self.verticalGroupBox1 = QtWidgets.QGroupBox(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.verticalGroupBox1.setFont(font)
        self.verticalGroupBox1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.verticalGroupBox1.setObjectName("verticalGroupBox1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalGroupBox1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.addsub = QtWidgets.QRadioButton(self.verticalGroupBox1)
        self.addsub.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.addsub.setChecked(True)
        self.addsub.setObjectName("addsub")
        self.verticalLayout_6.addWidget(self.addsub)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.verticalGroupBox1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.howmany = QtWidgets.QSpinBox(self.verticalGroupBox1)
        self.howmany.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.howmany.setMinimum(2)
        self.howmany.setMaximum(10000)
        self.howmany.setProperty("value", 10)
        self.howmany.setObjectName("howmany")
        self.horizontalLayout_7.addWidget(self.howmany)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.verticalGroupBox1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.digits = QtWidgets.QSpinBox(self.verticalGroupBox1)
        self.digits.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.digits.setMinimum(2)
        self.digits.setMaximum(7)
        self.digits.setProperty("value", 3)
        self.digits.setObjectName("digits")
        self.horizontalLayout_8.addWidget(self.digits)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3.addWidget(self.verticalGroupBox1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalGroupBox2 = QtWidgets.QGroupBox(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.verticalGroupBox2.setFont(font)
        self.verticalGroupBox2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.verticalGroupBox2.setObjectName("verticalGroupBox2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalGroupBox2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.simple = QtWidgets.QCheckBox(self.verticalGroupBox2)
        self.simple.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.simple.setChecked(True)
        self.simple.setObjectName("simple")
        self.horizontalLayout_11.addWidget(self.simple)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.complex5pos = QtWidgets.QCheckBox(self.verticalGroupBox2)
        self.complex5pos.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.complex5pos.setObjectName("complex5pos")
        self.horizontalLayout_12.addWidget(self.complex5pos)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.complex5neg = QtWidgets.QCheckBox(self.verticalGroupBox2)
        self.complex5neg.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.complex5neg.setObjectName("complex5neg")
        self.horizontalLayout_13.addWidget(self.complex5neg)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.complex10pos = QtWidgets.QCheckBox(self.verticalGroupBox2)
        self.complex10pos.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.complex10pos.setObjectName("complex10pos")
        self.horizontalLayout_14.addWidget(self.complex10pos)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.complex10neg = QtWidgets.QCheckBox(self.verticalGroupBox2)
        self.complex10neg.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.complex10neg.setObjectName("complex10neg")
        self.horizontalLayout_15.addWidget(self.complex10neg)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_9.addWidget(self.verticalGroupBox2)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.verticalGroupBox_2.setFont(font)
        self.verticalGroupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.checkBox = QtWidgets.QCheckBox(self.verticalGroupBox_2)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_16.addWidget(self.checkBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_6 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_17.addWidget(self.label_6)
        self.obstacles = QtWidgets.QSpinBox(self.verticalGroupBox_2)
        self.obstacles.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.obstacles.setMinimum(1)
        self.obstacles.setMaximum(3)
        self.obstacles.setObjectName("obstacles")
        self.horizontalLayout_17.addWidget(self.obstacles)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_9.addWidget(self.verticalGroupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton = QtWidgets.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_18.addWidget(self.pushButton)
        self.exit2 = QtWidgets.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.exit2.setFont(font)
        self.exit2.setObjectName("exit2")
        self.horizontalLayout_18.addWidget(self.exit2)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Soroban Trainer"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#00ff00;\">000</span></p></body></html>"))
        self.start.setText(_translate("MainWindow", "ابدأ"))
        self.save.setText(_translate("MainWindow", "حفظ العملية"))
        self.exit.setText(_translate("MainWindow", "الخروج من البرنامج"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainframe), _translate("MainWindow", "الواجهة الرئيسية"))
        self.verticalGroupBox.setTitle(_translate("MainWindow", "اعدادات الوقت"))
        self.label_2.setText(_translate("MainWindow", "وقت ظهور العدد"))
        self.label_3.setText(_translate("MainWindow", "وقت المسح"))
        self.verticalGroupBox1.setTitle(_translate("MainWindow", "اعدادات العمليات"))
        self.addsub.setText(_translate("MainWindow", "جمع و طرح"))
        self.label_4.setText(_translate("MainWindow", "طول العملية"))
        self.label_5.setText(_translate("MainWindow", "عدد الارقام في العدد"))
        self.verticalGroupBox2.setTitle(_translate("MainWindow", "نوع العمليات"))
        self.simple.setText(_translate("MainWindow", "بسيط"))
        self.complex5pos.setText(_translate("MainWindow", "مركب 5 موجب"))
        self.complex5neg.setText(_translate("MainWindow", "مركب 5 سالب"))
        self.complex10pos.setText(_translate("MainWindow", "مركب 10 موجب"))
        self.complex10neg.setText(_translate("MainWindow", "مركب 10 سالب"))
        self.verticalGroupBox_2.setTitle(_translate("MainWindow", "اعدادات الحواجز"))
        self.checkBox.setText(_translate("MainWindow", "اضافة حواجز "))
        self.label_6.setText(_translate("MainWindow", "مستوى الصعوبة"))
        self.pushButton.setText(_translate("MainWindow", "Excel استخراج ملف "))
        self.exit2.setText(_translate("MainWindow", "الخروج من البرنامج"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "الاعدادات"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">ASNF SOROBAN من طرف </span></p></body></html>"))

